"""
LORECAST agent: triggered on demand via POST /lorecast. Reads all LORE memories,
analyses staleness and health, and creates a formatted health report as a new
GitLab issue.
"""

import json
import logging
from datetime import datetime

from core.gitlab_client import GitLabClient
from core.claude_client import ClaudeClient
from core.memory import MemoryStore

logger = logging.getLogger("lore.lorecast")


async def run_lorecast() -> None:
    """
    Run LORECAST: fetch all memories, call Claude for health analysis, and
    create a GitLab issue with the formatted health report.
    """
    try:
        # — Step 1: Initialise clients —
        gitlab = GitLabClient()
        claude = ClaudeClient()
        memory_store = MemoryStore(gitlab)

        # — Step 2: Fetch all memories —
        all_memories = memory_store.get_all_memories()

        today_date = datetime.utcnow().strftime("%Y-%m-%d")

        if not all_memories:
            gitlab.create_issue(
                title=f"🧠 LORE Health Report — {today_date}",
                description=(
                    f"# 🧠 LORE Health Report — {today_date}\n\n"
                    "## No Memories Stored Yet\n\n"
                    "LORE is active and listening but no architectural decisions have been "
                    "captured yet.\n\n"
                    "**How to start building institutional memory:**\n"
                    "- LORE automatically captures decisions when MRs are merged\n"
                    "- Make sure the webhook is configured and active\n"
                    "- Decisions are extracted from MR discussion threads\n\n"
                    "*Generated by LORE LORECAST*"
                ),
                labels=["lore-health"],
            )
            return

        # — Step 3: Fetch recent MR titles —
        try:
            recent_mrs = gitlab.get_recent_mrs(count=20)
            recent_mr_titles = [m.get("title", "") for m in recent_mrs if m.get("title")]
        except Exception as e:
            logger.warning("LORECAST: Could not fetch recent MRs: %s", e)
            recent_mr_titles = []

        # — Step 4: Build the user message for Claude —
        memory_blocks = []
        for m in all_memories:
            governs = ", ".join(m.get("governs_files") or [])
            decided_by = ", ".join(m.get("decided_by") or [])
            memory_blocks.append(
                f"---\n"
                f"Memory #{m.get('id', '')}\n"
                f"Date captured: {m.get('date', '')}\n"
                f"Decision: {m.get('decision', '')}\n"
                f"Rejected: {m.get('rejected', '')}\n"
                f"Reason: {m.get('reason', '')}\n"
                f"Future implication: {m.get('future_implication', '')}\n"
                f"Governs files: {governs}\n"
                f"Decided by: {decided_by}\n"
                f"Confidence: {m.get('confidence', '')}\n"
                f"Status: {m.get('status', '')}\n"
                f"---"
            )
        all_memories_block = "\n\n".join(memory_blocks)

        if recent_mr_titles:
            recent_titles_block = "\n".join(f"{i+1}. {t}" for i, t in enumerate(recent_mr_titles))
        else:
            recent_titles_block = "No recent MRs found."

        user_message = (
            f"CURRENT DATE: {today_date}\n\n"
            f"ALL MEMORIES:\n{all_memories_block}\n\n"
            f"RECENT MR TITLES (last 20):\n{recent_titles_block}"
        )

        # — Step 5: Call Claude —
        system_prompt = claude.load_prompt("lorecast")
        response_str = claude.call(
            system_prompt=system_prompt,
            user_message=user_message,
            max_tokens=3000,
        )

        # — Step 6: Parse Claude response —
        try:
            result = json.loads(response_str)
        except json.JSONDecodeError as e:
            logger.error("LORECAST: Failed to parse Claude response: %s. Raw: %s", e, response_str)
            gitlab.create_issue(
                title=f"🧠 LORE Health Report — {today_date} (Parse Error)",
                description=response_str,
                labels=["lore-health"],
            )
            return

        # — Step 7: Build the formatted issue body —
        total_memories = result.get("total_memories", 0)
        healthy_count = result.get("healthy_count", 0)
        review_count = result.get("review_count", 0)
        stale_count = result.get("stale_count", 0)
        health_summary = result.get("health_summary", "")
        top_recommendation = result.get("top_recommendation", "")
        stale_memories = result.get("stale_memories") or []
        review_memories = result.get("review_memories") or []

        body_parts = [
            f"# 🧠 LORE Health Report — {today_date}",
            "",
            "## Summary",
            "",
            "| Metric | Count |",
            "|--------|-------|",
            f"| Total memories | {total_memories} |",
            f"| Healthy | {healthy_count} |",
            f"| Needs review | {review_count} |",
            f"| Potentially stale | {stale_count} |",
            "",
            "## Overall Health",
            health_summary,
            "",
            f"**Top recommendation:** {top_recommendation}",
            "",
            "",
        ]

        if stale_memories:
            body_parts.append("## ⚠️ Stale Memories — Action Required")
            body_parts.append("")
            for s in stale_memories:
                mem_id = s.get("memory_id", "")
                reason_stale = s.get("reason_stale", "")
                urgency = s.get("urgency", "")
                suggested_action = s.get("suggested_action", "")
                body_parts.append(f"### Memory #{mem_id}")
                body_parts.append(f"**Why potentially stale:** {reason_stale}")
                body_parts.append(f"**Urgency:** {urgency}")
                body_parts.append(f"**Suggested action:** {suggested_action}")
                body_parts.append("")

        if review_memories:
            body_parts.append("## 🔍 Memories Worth Reviewing")
            body_parts.append("")
            for r in review_memories:
                mem_id = r.get("memory_id", "")
                reason_review = r.get("reason_review", "")
                suggested_action = r.get("suggested_action", "")
                body_parts.append(f"### Memory #{mem_id}")
                body_parts.append(f"**Why:** {reason_review}")
                body_parts.append(f"**Suggested action:** {suggested_action}")
                body_parts.append("")

        if not stale_memories and not review_memories:
            body_parts.append("## ✅ All Memories Healthy")
            body_parts.append("")
            body_parts.append(
                "No stale or at-risk memories detected. Your institutional memory is in "
                "good shape."
            )
            body_parts.append("")

        body_parts.append("## Memory Growth")
        body_parts.append(f"Total memories stored: **{total_memories}**")
        body_parts.append(f"Report generated: {today_date}")
        body_parts.append("")
        body_parts.append("---")
        body_parts.append("*Generated by LORE LORECAST — your institutional memory health agent*")
        body_parts.append("*To run another health check: POST /lorecast*")

        formatted_body = "\n".join(body_parts)

        # — Step 8: Create the GitLab issue —
        created = gitlab.create_issue(
            title=f"🧠 LORE Health Report — {today_date}",
            description=formatted_body,
            labels=["lore-health"],
        )
        iid = created.get("iid")
        logger.info("LORECAST complete. Health report created as issue #%s.", iid)

    except Exception as e:
        logger.error("LORECAST failed: %s", e, exc_info=True)
        try:
            gitlab = GitLabClient()
            gitlab.create_issue(
                title="🧠 LORE Health Report — ERROR",
                description=f"LORECAST encountered an error: {str(e)}\n\nCheck server logs.",
                labels=["lore-health"],
            )
        except Exception:
            pass
